### ISSUE TITLE
XSS attack for anyone who opens btw.so

### ISSUE THREAD

**Issue by Keyruu** [btw-so/btw#36]
I just discovered this project through openalternatives.co and typed in the tryout thing. Then I added an HTML5 box and added a script tag with alert('test'). Now anyone that opens that page will receive that alert. Isn't that an easy XSS attack that should be prevented in the tryout page??

**Comment by siddug** [comment]
Hi @Keyruu Thanks for pointing this out. 

Once you sign up and use btw for your own blogging, this won't happen since you are adding code to your own site. 

However since the embedded portion on btw homepage is shared across visitors (for editing and viewing), this is an issue. 

Taking this up :) thanks for pointing it out.

**Comment by siddug** [comment]
Fix is live now.

**Comment by Keyruu** [comment]
Thank you for fixing this so fast!
